# Generated by Django 5.2.5 on 2025-08-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_virtual', models.BooleanField(default=True)),
                ('prize_pool', models.CharField(blank=True, max_length=100)),
                ('themes', models.CharField(blank=True, max_length=255)),
                ('sponsors', models.CharField(blank=True, max_length=255)),
                ('registration_deadline', models.DateTimeField()),
                ('requirements', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(choices=[('mlh', 'MLH'), ('devfolio', 'Devfolio'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('max_team_size', models.PositiveIntegerField(default=1)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteHackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hackathons', to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='hackathons.hackathon')),
            ],
            options={
                'unique_together': {('user', 'hackathon')},
            },
        ),
    ]
