# Generated by Django 5.2.5 on 2025-08-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='description',
        ),
    ]
