# Generated by Django 5.2.5 on 2025-08-13 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_hackathons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="is_user_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="platform",
            field=models.CharField(
                choices=[
                    ("mlh", "MLH"),
                    ("devfolio", "Devfolio"),
                    ("hackmate", "HackMate"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
