# Generated by Django 5.2.5 on 2025-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_remove_hackathon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='prizes',
            field=models.JSONField(default=dict, help_text="{'first': 50000, 'second': 30000}"),
        ),
        migrations.AlterField(
            model_name='hackathonapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('team_pending', 'Team Pending'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='applied', max_length=20),
        ),
    ]
