# Generated by Django 5.2.5 on 2025-08-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_alter_hackathon_prizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='short_description',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status', max_length=10),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
