# Generated by Django 5.2.5 on 2025-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_remove_hackathon_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
