# Generated by Django 5.2.5 on 2025-08-17 21:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0003_alter_hackathon_prizes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_members', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('looking', 'Looking for Members'), ('full', 'Full Team'), ('inactive', 'Inactive')], default='looking', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('looking_for_roles', models.JSONField(blank=True, default=list)),
                ('project_name', models.CharField(blank=True, max_length=150)),
                ('project_idea', models.TextField(blank=True)),
                ('github_repo', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('allow_remote', models.BooleanField(default=True)),
                ('preferred_timezone', models.CharField(blank=True, max_length=50)),
                ('communication_platform', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hackathons.hackathon')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Team Leader'), ('co-leader', 'Co-Leader'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('declined', 'Declined'), ('removed', 'Removed'), ('left', 'Left')], default='pending', max_length=20)),
                ('skills_contribution', models.JSONField(blank=True, default=list)),
                ('preferred_role_in_project', models.CharField(blank=True, max_length=100)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='teams.TeamMembership', through_fields=('team', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System')], default='text', max_length=20)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='team_files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teammessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teams.team')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('team', 'invitee')},
            },
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'status'], name='teams_teamm_user_id_e0b78b_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='teams_teamm_team_id_11426a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['hackathon', 'status'], name='teams_team_hackath_b3a520_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_leader', '-created_at'], name='teams_team_team_le_c5881c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'hackathon')},
        ),
        migrations.AddIndex(
            model_name='teammessage',
            index=models.Index(fields=['team', '-created_at'], name='teams_teamm_team_id_dd376d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammessage',
            index=models.Index(fields=['sender', '-created_at'], name='teams_teamm_sender__035a4d_idx'),
        ),
    ]
