# Generated by Django 5.2.5 on 2025-08-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='communication_platform',
        ),
        migrations.RemoveField(
            model_name='team',
            name='preferred_timezone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='privacy',
        ),
    ]
