# Generated by Django 5.2.5 on 2025-08-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_communication_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('leader_pending', 'Waiting for Leader Approval'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rejected', 'Rejected by Leader'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
