# Generated by Django 5.2.5 on 2025-08-13 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hackathons", "0002_hackathon_created_by_hackathon_is_published_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requires_portfolio", models.BooleanField(default=False)),
                ("requires_resume", models.BooleanField(default=False)),
                ("requires_github", models.BooleanField(default=False)),
                ("requires_linkedin", models.BooleanField(default=False)),
                ("custom_question_1", models.TextField(blank=True)),
                ("custom_question_2", models.TextField(blank=True)),
                ("custom_question_3", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hackathon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_form",
                        to="hackathons.hackathon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HackathonApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_role",
                    models.CharField(
                        choices=[
                            ("developer", "Developer"),
                            ("designer", "Designer"),
                            ("pm", "Product Manager"),
                            ("marketing", "Marketing"),
                            ("data_scientist", "Data Scientist"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("motivation", models.TextField(help_text="Why do you want to join?")),
                ("goals", models.TextField(help_text="What do you hope to achieve?")),
                ("preferred_team_size", models.PositiveIntegerField(default=4)),
                (
                    "previous_hackathon_experience",
                    models.CharField(
                        choices=[
                            ("first_time", "First Time"),
                            ("1-2", "1-2 Hackathons"),
                            ("3-5", "3-5 Hackathons"),
                            ("5+", "5+ Hackathons"),
                        ],
                        max_length=15,
                    ),
                ),
                ("portfolio_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hackathons.hackathon",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hackathon_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "hackathon")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_answer_1", models.TextField(blank=True)),
                ("custom_answer_2", models.TextField(blank=True)),
                ("custom_answer_3", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_responses",
                        to="hackathon_applications.hackathonapplication",
                    ),
                ),
            ],
        ),
    ]
