# Generated by Django 5.2.5 on 2025-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackerrank_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leetcode_url',
            field=models.URLField(blank=True),
        ),
    ]
