# Generated by Django 5.2.5 on 2025-08-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hackerrank_url_user_leetcode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hackerrank_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
