# Generated by Django 5.2.5 on 2025-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_hackerrank_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_hackathons',
            new_name='total_hackathons_participated',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant/User'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='participant', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_hackathons_organized',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
