# Generated by Django 5.2.5 on 2025-08-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_total_hackathons_user_total_hackathons_participated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hackathons_won',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_hackathons_organized',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_hackathons_participated',
        ),
    ]
